### ISSUE TITLE
Make ci-robot admin to support auto updates on staging

### ISSUE THREAD

**Issue by anderson-amorim** [coingaming/stacksUpdate-orb#35]
## Describe Request:
Can you make the ci-robot(robot@coingaming.io) admin on circle ci so we can configure auto updates on staging branch as well?
In casino team we generate staging pre-release tags and having to open a PR for them every single time is very annoying.

## Examples:
```
- stacks-update/update-service-version:
          context: global
          branch: staging
          stack: casino-sites
          repo: git@github.com:coingaming/stacks.git
          git_email: robot@coingaming.io
          requires:
            - build-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(?=.*v)(?=.*staging).*/
```
